name: jfbfestival
description: "The official mobile application for the Japan Festival Boston"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+3

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.2
  device_preview: ^1.1.0
  motion: ^2.0.1
  provider: ^6.0.0
  flutter_blur: ^0.0.2
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  url_launcher: ^6.0.9
  share_plus: ^10.1.4
  hive: ^2.2.3 # core Hive package
  hive_flutter: ^1.1.0
  supabase: ^2.6.0
  flutter_local_notifications: ^17.1.0 # latest at time of writing
  timezone: ^0.9.4
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.0.15
  geolocator: ^13.0.0
  google_fonts: ^6.2.1
  collection: ^1.19.1
  cached_network_image: ^3.4.1
  http: ^1.6.0

dependency_overrides:
  video_player_avfoundation: ^2.9.2
#   sign_in_with_apple: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.0 # to generate type adapters
  build_runner: ^2.4.0 # to run code generation
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/filter(white).png
    - assets/JFBLogo.png
    - assets/JFBHomeImage.png
    - assets/map.png
    - assets/Filter.png
    - assets/payments/
    - assets/allergens/

    # Splash Screen
    - assets/Intro1.mp4

    # Home Page Socials
    - assets/instagram.png
    - assets/facebook.png
    - assets/website.png

    # Maps
    - assets/MapNew.png
    - assets/MapNew1.png
    - assets/MapNew2.png
    - assets/MapNew3.png
    - assets/MapNew4.png

    # Home page images
    - assets/JFB-4.jpg
    - assets/JFB-3.jpg
    - assets/JFB-8.jpg
    - assets/JFB-15.jpg
    - assets/JFB-10.jpg
    - assets/JFB-22.jpg
    - assets/JFB-27.jpg
    - assets/JFB-6.jpg

    - assets/allergens/tree_nut.png
    - assets/allergens/milk.png
    - assets/allergens/fish.png
    - assets/allergens/soy.png
    - assets/allergens/egg.png
    - assets/vegetarian.png
    - assets/HomeImage1.jpg
    - assets/HomeImage2.jpg
    - assets/HomeImage3.jpg
    - assets/HomeImage4.jpg
    - assets/HomeImage5.jpg
    - assets/HomeImage6.jpg

    # Page selection bar
    - assets/bottomBar/Map.png
    - assets/bottomBar/Timetable.png
    - assets/bottomBar/Home.png
    - assets/bottomBar/Food.png
    - assets/bottomBar/Map(Frame).png
    - assets/bottomBar/Timetable(Frame).png
    - assets/bottomBar/Home(Frame).png
    - assets/bottomBar/Food(Frame).png

    # Event icons
    - assets/timetableIcons/Advertising.png
    - assets/timetableIcons/Advertising (Frame).png
    - assets/timetableIcons/Anime stage (Frame).png
    - assets/timetableIcons/Anime stage.png
    - assets/timetableIcons/Dancing performance (Frame).png
    - assets/timetableIcons/Dancing performance.png
    - assets/timetableIcons/Opening ceremony (Frame).png
    - assets/timetableIcons/Opening ceremony.png
    - assets/timetableIcons/Singing performance (Frame).png
    - assets/timetableIcons/Singing performance.png
    - assets/timetableIcons/Band performance.png
    - assets/timetableIcons/Band performance (Frame).png
    - assets/timetableIcons/Kendo.png
    - assets/timetableIcons/Kendo (Frame).png
    - assets/timetableIcons/Closing ceremony.png
    - assets/timetableIcons/Closing ceremony (Frame).png
    - assets/timetableIcons/taiko.png
    - assets/timetableIcons/taiko(frame).png

    # Downtown Poster
    - assets/JFBDowntownPoster.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
        - asset: assets/fonts/Fredoka-Light.ttf
        - asset: assets/fonts/NotoSansJP-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/jfbostonIconWhiteBg.png"
  adaptive_icon_background: "#ffffff" # Android supplies the white bg
  adaptive_icon_foreground: "assets/jfbostonIconNoBg.png"
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
